### PR TITLE
Update lti utils fixes issue #248 #247

### PR DESCRIPTION
**Pull request by jonespm**

### CODE REVIEW

**Comment by jonespm** [comment]
I only tested that this builds and pulls down the updated dependency. I didn't test if this ran.

**Comment by pushyamig** [comment]
I will upgrade to 4.5.6, test and will resolve it as separate issue.

**Comment by jonespm** [comment]
Doh! I already added that change to this PR. ;)

**Comment by pushyamig** [comment]
That's ok, I will do the testing part

**Comment by pushyamig** [comment]
The version update `4.5.6` seems to be good with testing

**Comment by jonespm** [comment]
Going to merge this one since you've verified it. Thanks!

**Pull request merged**
